### ISSUE TITLE
Check initial state early

### ISSUE THREAD

**Issue by Kha** [parttimenerd/WhileSemantic#3]
Do not try to execute program (and fail) if the initial state's domain does not cover the set of used variables.

```
<b := c, {}> --> "this.value is undefined"
<{var x := 1; skip}, {}> --> "funcs[com.constructor.name] is undefined" (only using SS semantics)
```

**Comment by parttimenerd** [comment]
I would prefer to treat all variables as having ⊥ as their initial value.

**Comment by Kha** [comment]
In the lecture notes states are total, but that's a sensible generalization.
